name: Flutter CI

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            
            - name: Set up Flutter
              uses: subosito/flutter-action@v2
              with:
                flutter-version: '3.4.4'
            - run: flutter pub get
            - run: flutter test
            - run: flutter build apk 
            - run: flutter bulid appbundle
        
            - name: Build ios
              if: runner.os == 'macOS'
              run: flutter build ios

            
            
